
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mule-ui-stable
spec:
  replicas: {{ .Values.spec.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1  
  template:
    metadata:
      labels:
        app: mule-ui
        track: stable
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: mule-ui
        ports:
        - containerPort: 8080
          name: mule-ui
