apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mule-app-green
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mule-app
        color: green
    spec:
      containers:
      - image: vishalbiyani/mule-app:latest
        name: mule-app
        ports:
        - containerPort: 8081
          name: mule-app
