apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mule-app-stable
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mule-app
        track: stable
    spec:
      containers:
      - image: vishalbiyani/mule-app:replaceTagName
        name: mule-app
        ports:
        - containerPort: 8081
          name: mule-app
