apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mule-ui-canary
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1  
  template:
    metadata:
      labels:
        app: mule-ui
        track: canary
    spec:
      containers:
      - image: vishalbiyani/mule-ui:latest
        name: mule-ui
        ports:
        - containerPort: 8080
          name: mule-ui
