apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mule-ui
  labels:
    app: mule-ui
spec:
  replicas:
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mule-ui
        color: green
    spec:
      containers:
      - image: vishalbiyani/mule-ui:latest
        name: mule-ui
        ports:
        - containerPort: 8080
          name: mule-ui