apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mule-ui
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mule-ui
        color: blue
    spec:
      containers:
      - image: vishalbiyani/mule-ui:latest
        name: mule-ui
        ports:
        - containerPort: 8080
          name: mule-ui
