node {
    
    checkout scm

    imageName = "mule-app"

        stage('Backend Build') {
                docker build -t vishalbiyani/mule-app .
        }
        stage('Backend Push') {
                docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
                    def customImage = docker.build("${imageName}", "-f Dockerfile .")
                    customImage.push()
                }
        }
}
