# Default values for test-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
spec:
  replicaCount: 2
image:
  repository: vishalbiyani/mule-ui
  tag: jenkins-mule-master-23
